const c=document.getElementById("canvas"),x=c.getContext("2d"),overlay=document.getElementById("overlay"),start=document.getElementById("start"),scoreEl=document.getElementById("score"),healthEl=document.getElementById("health"),waveEl=document.getElementById("wave"),msg=document.getElementById("message");
let W,H,dpr,keys={},running=false,score=0,health=100,wave=1,last=0,spawn=0,bossTimer=0,shots=[],enemies=[],enemyShots=[],particles=[],powerups=[],stars=[],weapon=0,upgrade={damage:1,fireRate:1,shield:0},audio;
const weapons=[{name:"Pulse",cool:.18,damage:1,spread:0},{name:"Twin Laser",cool:.22,damage:1,spread:11},{name:"Plasma",cool:.34,damage:3,spread:0}];
const ship={x:0,y:0,r:18,speed:340,cool:0,flash:0};
function resize(){dpr=devicePixelRatio||1;W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0);ship.x=W/2;ship.y=H-90;stars=Array.from({length:150},()=>({x:Math.random()*W,y:Math.random()*H,s:20+Math.random()*120,z:1+Math.random()*2}))}
addEventListener("resize",resize);
addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.code==="Space")e.preventDefault();if(e.key.toLowerCase()==="r"&&!running)startGame()});
addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);start.onclick=startGame;
function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
function tone(freq,dur=.06,type="sine",gain=.035){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function startGame(){initAudio();score=0;health=100;wave=1;weapon=0;upgrade={damage:1,fireRate:1,shield:0};shots=[];enemies=[];enemyShots=[];particles=[];powerups=[];running=true;bossTimer=0;spawn=.5;overlay.classList.add("hidden");ship.x=W/2;ship.y=H-90;last=performance.now();tone(220,.18,"sawtooth",.05);requestAnimationFrame(loop)}
function burst(px,py,color,count=18){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*220;particles.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.5,size:2+Math.random()*4,color})}tone(90,.08,"sawtooth",.025)}
function fire(){if(ship.cool>0)return;const w=weapons[weapon],cd=w.cool/upgrade.fireRate;for(const off of weapon===1?[-w.spread,w.spread]:[0])shots.push({x:ship.x+off,y:ship.y-22,r:weapon===2?7:4,v:720,damage:w.damage*upgrade.damage});ship.cool=cd;tone(weapon===2?150:620,.045,weapon===2?"sawtooth":"square",.025)}
function spawnEnemy(forceBoss=false){if(forceBoss){enemies.push({boss:true,x:W/2,y:-100,r:62,hp:80+wave*15,max:80+wave*15,v:35,t:0,shoot:1});return}const q=Math.random(),type=q>.82?"tank":q>.55?"zig":"scout";enemies.push({type,x:35+Math.random()*(W-70),y:-35,r:type==="tank"?27:17,hp:type==="tank"?5:1,v:(65+wave*8)+(type==="scout"?45:0),t:Math.random()*7,shoot:1+Math.random()*2})}
function enemyFire(e){if(e.y<0)return;const a=Math.atan2(ship.y-e.y,ship.x-e.x),speed=e.boss?180:150;enemyShots.push({x:e.x,y:e.y,r:e.boss?7:5,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed});tone(180,.04,"triangle",.015)}
function drop(x,y){if(Math.random()<.14)powerups.push({x,y,r:11,type:Math.floor(Math.random()*4),life:9})}
function hit(a,b){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r}
function damagePlayer(n){const d=Math.max(0,n-upgrade.shield*5);if(d){health-=d;ship.flash=.12;tone(75,.08,"sawtooth",.04)}}
function update(dt){let dx=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0),dy=(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0),len=Math.hypot(dx,dy)||1;ship.x=Math.max(22,Math.min(W-22,ship.x+dx/len*ship.speed*dt));ship.y=Math.max(35,Math.min(H-30,ship.y+dy/len*ship.speed*dt));if(keys[" "]||keys.space)fire();ship.cool=Math.max(0,ship.cool-dt);ship.flash=Math.max(0,ship.flash-dt);
spawn-=dt;bossTimer+=dt;if(spawn<=0&&!enemies.some(e=>e.boss)){spawnEnemy();spawn=Math.max(.25,1-wave*.035)}
if(bossTimer>28&&!enemies.some(e=>e.boss)){spawnEnemy(true);bossTimer=0;tone(55,.5,"sawtooth",.07)}
stars.forEach(s=>{s.y+=s.s*dt*(1+wave*.025);if(s.y>H){s.y=0;s.x=Math.random()*W}});
shots.forEach(b=>b.y-=b.v*dt);shots=shots.filter(b=>b.y>-30);
enemyShots.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});enemyShots=enemyShots.filter(b=>b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);
enemies.forEach(e=>{e.y+=e.v*dt;e.t+=dt;if(!e.boss)e.x+=Math.sin(e.t*2.2)*35*dt;e.shoot-=dt;if(e.shoot<=0){enemyFire(e);e.shoot=e.boss?.65:2+Math.random()*2}if(e.y>H+50){damagePlayer(e.boss?25:10);e.y=-60}});
for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];for(let j=shots.length-1;j>=0;j--)if(hit(e,shots[j])){e.hp-=shots[j].damage;burst(shots[j].x,shots[j].y,"#72e8ff",4);shots.splice(j,1);if(e.hp<=0){score+=e.boss?1000:e.r>20?100:25;drop(e.x,e.y);burst(e.x,e.y,e.boss?"#ff3f7f":"#ffb347",e.boss?55:20);enemies.splice(i,1);if(e.boss)wave++;break}}if(enemies[i]&&hit(ship,enemies[i])){damagePlayer(enemies[i].boss?35:20);burst(ship.x,ship.y,"#ff5470",15);enemies.splice(i,1)}}
for(let i=enemyShots.length-1;i>=0;i--)if(hit(ship,enemyShots[i])){damagePlayer(10);burst(ship.x,ship.y,"#ff5470",7);enemyShots.splice(i,1)}
for(let i=powerups.length-1;i>=0;i--){let p=powerups[i];p.y+=70*dt;p.life-=dt;if(hit(ship,p)){if(p.type===0)weapon=(weapon+1)%3;if(p.type===1)upgrade.damage=Math.min(4,upgrade.damage+1);if(p.type===2)health=Math.min(100,health+25);if(p.type===3)upgrade.shield=Math.min(5,upgrade.shield+1);score+=50;tone(880,.12,"sine",.05);powerups.splice(i,1)}else if(p.life<=0)powerups.splice(i,1)}
particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt});particles=particles.filter(p=>p.life>0);
scoreEl.textContent=score;healthEl.textContent=Math.max(0,Math.ceil(health));waveEl.textContent=wave;if(health<=0)endGame()}
function drawShip(){x.save();x.translate(ship.x,ship.y);x.globalAlpha=ship.flash?0.45:1;x.shadowBlur=22;x.shadowColor="#5de4ff";x.fillStyle="#5de4ff";x.beginPath();x.moveTo(0,-27);x.lineTo(-21,21);x.lineTo(0,13);x.lineTo(21,21);x.closePath();x.fill();x.fillStyle="#dffaff";x.beginPath();x.arc(0,-5,5,0,Math.PI*2);x.fill();x.fillStyle="#ffb347";x.beginPath();x.moveTo(-7,18);x.lineTo(0,32+Math.random()*7);x.lineTo(7,18);x.fill();x.restore()}
function draw(){x.clearRect(0,0,W,H);x.fillStyle="#fff";stars.forEach(s=>{x.globalAlpha=.25+s.z*.2;x.fillRect(s.x,s.y,s.z,s.z*2)});x.globalAlpha=1;
shots.forEach(b=>{x.fillStyle=weapon===2?"#d36bff":"#72e8ff";x.shadowBlur=15;x.shadowColor=x.fillStyle;x.beginPath();x.arc(b.x,b.y,b.r,0,Math.PI*2);x.fill()});
enemyShots.forEach(b=>{x.fillStyle="#ff527d";x.shadowBlur=12;x.shadowColor="#ff527d";x.beginPath();x.arc(b.x,b.y,b.r,0,Math.PI*2);x.fill()});
enemies.forEach(e=>{x.save();x.translate(e.x,e.y);x.rotate(Math.sin(e.t)*.12);x.shadowBlur=e.boss?30:16;x.shadowColor=e.boss?"#ff3f7f":e.type==="tank"?"#b879ff":"#ffb347";x.fillStyle=e.boss?"#ff3f7f":e.type==="tank"?"#b879ff":"#ffb347";x.beginPath();if(e.boss){x.arc(0,0,e.r,0,Math.PI*2);x.fill();x.fillStyle="#14051d";x.beginPath();x.arc(0,0,e.r*.45,0,Math.PI*2);x.fill()}else{x.moveTo(0,e.r);x.lineTo(-e.r,-e.r);x.lineTo(0,-e.r*.35);x.lineTo(e.r,-e.r);x.closePath();x.fill()}x.restore();if(e.boss){x.fillStyle="#30111d";x.fillRect(e.x-70,e.y-e.r-18,140,7);x.fillStyle="#ff4e7d";x.fillRect(e.x-70,e.y-e.r-18,140*Math.max(0,e.hp/e.max),7)}});
powerups.forEach(p=>{const labels=["W","D","+","S"];x.fillStyle="#fff";x.shadowBlur=18;x.shadowColor="#6ee7ff";x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fill();x.fillStyle="#09203a";x.font="bold 13px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText(labels[p.type],p.x,p.y)});
particles.forEach(p=>{x.globalAlpha=Math.max(0,p.life*2);x.fillStyle=p.color;x.fillRect(p.x,p.y,p.size,p.size)});x.globalAlpha=1;x.shadowBlur=0;drawShip();
x.fillStyle="#b9d8ff";x.font="12px system-ui";x.textAlign="left";x.fillText("Weapon: "+weapons[weapon].name+"  |  Damage Lv."+upgrade.damage+"  |  Shield Lv."+upgrade.shield,22,H-18)}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
function endGame(){running=false;msg.textContent="Mission failed — press R or launch again.";start.textContent="RESTART MISSION";overlay.classList.remove("hidden");tone(55,.4,"sawtooth",.06)}
resize();draw();