import { generateLevel, type GeneratedLevel, type Spawn } from "./levels";

type ShipId="viper"|"nova"|"titan";
type WeaponId="pulse"|"twin"|"plasma"|"rail";
type UpgradeKey="damage"|"fireRate"|"shield"|"hull";
type Mode="hangar"|"game"|"pause"|"results";
type Save={version:number,credits:number,xp:number,level:number,selected:ShipId,ships:Record<ShipId,boolean>,weapon:WeaponId,unlockedWeapons:Record<WeaponId,boolean>,upgrades:Record<UpgradeKey,number>,completed:number[],best:number,achievements:string[]};
type Entity={x:number,y:number,r:number,hp:number,max:number,type:string,t:number,cool:number,vx:number,vy:number,elite?:boolean,boss?:boolean,phase?:number};
type Bullet={x:number,y:number,r:number,damage:number,vx:number,vy:number,life:number,pierce:number};
type Particle={x:number,y:number,vx:number,vy:number,life:number,size:number,text:string};
type Drop={x:number,y:number,r:number,type:"heal"|"rapid"|"shield"|"bomb"|"credits",life:number};

const canvas=document.querySelector<HTMLCanvasElement>("#canvas")!,ctx=canvas.getContext("2d")!;
const overlay=document.querySelector<HTMLElement>("#overlay")!,panel=document.querySelector<HTMLElement>("#panel")!,action=document.querySelector<HTMLButtonElement>("#action")!;
const KEY="interstella-save-v7";
const SHIPS=[
{id:"viper" as ShipId,name:"VIPER",speed:470,hull:95,price:0,unlock:1,ability:"DASH"},
{id:"nova" as ShipId,name:"NOVA",speed:400,hull:130,price:900,unlock:3,ability:"RAPID FIRE"},
{id:"titan" as ShipId,name:"TITAN",speed:325,hull:180,price:1800,unlock:6,ability:"FORTIFY"}
];
const WEAPONS=[
{id:"pulse" as WeaponId,name:"PULSE",cool:.16,damage:12,price:0,unlock:1,pierce:0},
{id:"twin" as WeaponId,name:"TWIN LASER",cool:.21,damage:10,price:600,unlock:2,pierce:0},
{id:"plasma" as WeaponId,name:"PLASMA",cool:.34,damage:38,price:1200,unlock:4,pierce:1},
{id:"rail" as WeaponId,name:"RAIL CANNON",cool:.58,damage:88,price:2400,unlock:7,pierce:3}
];
const fresh=():Save=>({version:7,credits:0,xp:0,level:1,selected:"viper",ships:{viper:true,nova:false,titan:false},weapon:"pulse",unlockedWeapons:{pulse:true,twin:false,plasma:false,rail:false},upgrades:{damage:1,fireRate:1,shield:0,hull:0},completed:[],best:0,achievements:[]});
function load():Save{try{const r=JSON.parse(localStorage.getItem(KEY)||"null"),b=fresh();return {...b,...r,upgrades:{...b.upgrades,...r?.upgrades},ships:{...b.ships,...r?.ships},unlockedWeapons:{...b.unlockedWeapons,...r?.unlockedWeapons}}}catch{return fresh()}}
let save=load(),W=0,H=0,mode:Mode="hangar",level=1,world:GeneratedLevel=generateLevel(1),spawnIndex=0,running=false,last=0,time=0,score=0,hp=0,combo=0,comboTimer=0,shake=0,flash=0,dash=0,dashCooldown=0,rapid=0,shieldBoost=0;
let bullets:Bullet[]=[],enemyBullets:Bullet[]=[],enemies:Entity[]=[],particles:Particle[]=[],drops:Drop[]=[],stars:{x:number,y:number,s:number}[]=[],keys=new Set<string>(),audio:AudioContext|null=null,touchReady=false;
const player={x:0,y:0,r:19,cool:0},touch={x:0,y:0,fire:false};
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const persist=()=>localStorage.setItem(KEY,JSON.stringify(save));
const xpNeed=()=>Math.floor(260*Math.pow(save.level,1.38));
function snd(f:number,d=.06){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.025;g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function audioOn(){audio??=new AudioContext();void audio.resume()}
function burst(x:number,y:number,n=18,text="#72e8ff"){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*300;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.7,size:1+Math.random()*4,text})}shake=Math.min(18,shake+n*.18)}
function toast(t:string){particles.push({x:W/2,y:H*.24,vx:0,vy:-12,life:1.4,size:22,text:t})}
function gainXP(n:number){save.xp+=n;while(save.level<30&&save.xp>=xpNeed()){save.xp-=xpNeed();save.level++;burst(player.x,player.y,35,"#7dffcf");toast("LEVEL UP "+save.level)}persist()}
function resize(){W=innerWidth;H=innerHeight;const d=devicePixelRatio||1;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);player.x=clamp(player.x||W/2,24,W-24);player.y=clamp(player.y||H-90,45,H-45);stars=Array.from({length:Math.min(240,Math.floor(W*H/5200))},()=>({x:Math.random()*W,y:Math.random()*H,s:25+Math.random()*150}))}
function renderHangar(note=""){mode="hangar";running=false;overlay.classList.remove("hidden");document.body.dataset.mode="hangar";world=generateLevel(level);const s=SHIPS.find(x=>x.id===save.selected)!,w=WEAPONS.find(x=>x.id===save.weapon)!;
panel.innerHTML="<div class='brand'>INTERSTELLA</div><div class='eyebrow'>COMMAND DECK · GALAXY FRONT</div><div class='topstats'><b>LV "+save.level+"</b><span>"+save.xp+"/"+xpNeed()+" XP</span><b>"+save.credits.toLocaleString()+" CR</b><span>"+save.completed.length+"/30 CLEARED</span></div><div class='xpbar'><i style='width:"+clamp(save.xp/xpNeed()*100,0,100)+"%'></i></div><div class='cards'><article class='card mission'><label>NEXT OPERATION</label><h2>"+world.name+"</h2><p>"+world.kind.toUpperCase()+" · "+(world.kind==="boss"?"BOSS THREAT DETECTED":world.kind==="survival"?"SURVIVE THE ONSLAUGHT":world.kind==="escort"?"PROTECT THE CONVOY":"LIBERATE THE SECTOR")+"</p><small>SEED "+world.seed+" · "+Math.ceil(world.duration)+"s · "+world.spawns.length+" CONTACTS</small></article><article class='card'><label>SHIP</label><h2>"+s.name+"</h2><p>"+s.ability+"</p><small>HULL "+(s.hull+save.upgrades.hull*12)+" · SPEED "+s.speed+"</small></article><article class='card'><label>WEAPON</label><h2>"+w.name+"</h2><p>"+w.damage+" BASE DAMAGE</p><small>COOLDOWN "+w.cool.toFixed(2)+"s · PIERCE "+w.pierce+"</small></article></div><div class='grid'><button id='ship'>CHANGE / BUY SHIP</button><button id='weapon'>CHANGE / BUY WEAPON</button><button id='dmg'>DAMAGE "+save.upgrades.damage+"/8</button><button id='fir'>FIRE RATE "+save.upgrades.fireRate+"/8</button><button id='sh'>SHIELD "+save.upgrades.shield+"/8</button><button id='hu'>HULL "+save.upgrades.hull+"/8</button></div><div class='hint'>"+(note||"Build your loadout, then launch. Every sector is deterministic from its seed.")+"</div>";
action.textContent="LAUNCH OPERATION";action.onclick=launch;
panel.querySelector("#ship")?.addEventListener("click",cycleShip);panel.querySelector("#weapon")?.addEventListener("click",cycleWeapon);panel.querySelector("#dmg")?.addEventListener("click",()=>buy("damage"));panel.querySelector("#fir")?.addEventListener("click",()=>buy("fireRate"));panel.querySelector("#sh")?.addEventListener("click",()=>buy("shield"));panel.querySelector("#hu")?.addEventListener("click",()=>buy("hull"))}
function buy(k:UpgradeKey){const price=180+save.upgrades[k]*170+save.level*20;if(save.upgrades[k]>=8)return toast("MAX LEVEL");if(save.credits<price)return toast("NEED "+price+" CR");save.credits-=price;save.upgrades[k]++;persist();renderHangar("UPGRADE INSTALLED · "+k.toUpperCase())}
function cycleShip(){const i=SHIPS.findIndex(s=>s.id===save.selected),n=SHIPS[(i+1)%SHIPS.length];if(save.level<n.unlock)return toast("SHIP REQUIRES LEVEL "+n.unlock);if(!save.ships[n.id]){if(save.credits<n.price)return toast("NEED "+n.price+" CR");save.credits-=n.price;save.ships[n.id]=true}save.selected=n.id;persist();renderHangar(n.name+" READY")}
function cycleWeapon(){const i=WEAPONS.findIndex(w=>w.id===save.weapon),n=WEAPONS[(i+1)%WEAPONS.length];if(save.level<n.unlock)return toast("WEAPON REQUIRES LEVEL "+n.unlock);if(!save.unlockedWeapons[n.id]){if(save.credits<n.price)return toast("NEED "+n.price+" CR");save.credits-=n.price;save.unlockedWeapons[n.id]=true}save.weapon=n.id;persist();renderHangar(n.name+" EQUIPPED")}
function launch(){audioOn();world=generateLevel(level);mode="game";running=true;overlay.classList.add("hidden");document.body.dataset.mode="game";spawnIndex=0;time=0;score=0;combo=0;comboTimer=0;dash=0;dashCooldown=0;rapid=0;shieldBoost=0;bullets=[];enemyBullets=[];enemies=[];particles=[];drops=[];hp=SHIPS.find(s=>s.id===save.selected)!.hull+save.upgrades.hull*12;player.x=W/2;player.y=H-90;last=performance.now();snd(260,.18);requestAnimationFrame(loop)}
function fire(){if(player.cool>0)return;const w=WEAPONS.find(v=>v.id===save.weapon)!,d=w.damage*(1+save.upgrades.damage*.2)*(save.selected==="nova"?1.05:save.selected==="titan"?1.12:1),offs=save.weapon==="twin"?[-12,12]:[0];for(const ox of offs)bullets.push({x:player.x+ox,y:player.y-24,r:save.weapon==="plasma"?8:5,damage:d,vx:0,vy:save.weapon==="rail"?-1050:-820,life:1.6,pierce:w.pierce});player.cool=w.cool/(1+save.upgrades.fireRate*.11)/(rapid>0?2.2:1);snd(save.weapon==="rail"?100:save.weapon==="plasma"?180:620,.035)}
function spawnFrom(s:Spawn){const hp=(s.kind==="tank"?95:s.kind==="elite"?190:s.kind==="swarmer"?18:32)*(1+level*.055);enemies.push({x:s.x*W,y:-40,r:s.kind==="tank"?28:s.kind==="elite"?25:s.kind==="swarmer"?11:17,hp,max:hp,type:s.kind,t:0,cool:.7+Math.random()*1.5,vx:0,vy:60+level*3,elite:s.kind==="elite"})}
function spawnBoss(){const final=level%10===0,max=(final?1700:650)+level*45;enemies.push({x:W/2,y:-100,r:final?76:58,hp:max,max,type:final?"DREADNOUGHT":"GUARDIAN",t:0,cool:.6,vx:0,vy:28,boss:true,phase:1});toast(final?"DREADNOUGHT INBOUND":"BOSS INBOUND");snd(90,.5)}
function drop(x:number,y:number){if(Math.random()>.16)return;const a:Drop["type"][]=["heal","rapid","shield","bomb","credits"];drops.push({x,y,r:13,type:a[Math.floor(Math.random()*a.length)],life:12})}
function kill(e:Entity){const reward=e.boss?500+level*30:e.elite?75:e.type==="tank"?32:e.type==="swarmer"?8:16;score+=reward;save.credits+=reward;gainXP(e.boss?300:e.elite?55:10);combo++;comboTimer=3;save.credits+=Math.floor(reward*Math.min(combo,12)*.04);drop(e.x,e.y);burst(e.x,e.y,e.boss?70:e.elite?35:18,e.boss?"#ff3f7f":e.elite?"#c779ff":"#ffb347");snd(e.boss?70:e.elite?190:420,.08)}
function damagePlayer(n:number){const reduction=save.upgrades.shield*3+(shieldBoost>0?25:0);hp-=Math.max(1,n-reduction);flash=.15;shake=8;snd(70,.08)}
function dashNow(){if(dashCooldown>0||mode!=="game")return;dash=.18;dashCooldown=1.15;burst(player.x,player.y,12,"#72e8ff");snd(900,.06)}
function update(dt:number){if(mode!=="game")return;time+=dt;comboTimer-=dt;if(comboTimer<=0)combo=0;dashCooldown=Math.max(0,dashCooldown-dt);dash=Math.max(0,dash-dt);rapid=Math.max(0,rapid-dt);shieldBoost=Math.max(0,shieldBoost-dt);player.cool=Math.max(0,player.cool-dt);flash=Math.max(0,flash-dt);
let dx=(keys.has("a")||keys.has("arrowleft")?-1:0)+(keys.has("d")||keys.has("arrowright")?1:0)+touch.x,dy=(keys.has("w")||keys.has("arrowup")?-1:0)+(keys.has("s")||keys.has("arrowdown")?1:0)+touch.y,l=Math.hypot(dx,dy)||1;const sp=SHIPS.find(s=>s.id===save.selected)!.speed;player.x=clamp(player.x+dx/l*sp*dt*(dash>0?3.4:1),24,W-24);player.y=clamp(player.y+dy/l*sp*dt*(dash>0?3.4:1),45,H-45);if(keys.has(" ")||keys.has("space")||touch.fire)fire();
stars.forEach(s=>{s.y+=s.s*dt*(dash>0?2.5:1);if(s.y>H)s.y=0});
while(spawnIndex<world.spawns.length&&world.spawns[spawnIndex].t<=time)spawnFrom(world.spawns[spawnIndex++]);if(world.kind==="boss"&&!enemies.some(e=>e.boss)&&time>=Math.max(7,world.duration*.3))spawnBoss();
for(const e of enemies){e.t+=dt;e.y+=e.vy*dt;if(e.type==="zig")e.x+=Math.sin(e.t*3.2)*90*dt;if(e.type==="swarmer")e.x+=Math.sin(e.t*8)*140*dt;if(e.boss){e.x=W/2+Math.sin(e.t*.7)*W*.3;e.phase=e.hp<e.max*.66?2:e.hp<e.max*.33?3:1;e.vy=e.phase===3?48:28}e.cool-=dt;if(e.cool<=0){const a=Math.atan2(player.y-e.y,player.x-e.x),speed=e.boss?220+(e.phase||1)*35:150+level*3;enemyBullets.push({x:e.x,y:e.y,r:e.boss?8:5,damage:e.boss?16:10,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:5,pierce:0});e.cool=e.boss?.45:1.3+Math.random()*1.8}}
for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}bullets=bullets.filter(b=>b.life>0&&b.y>-60);
for(const b of enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}enemyBullets=enemyBullets.filter(b=>b.life>0&&b.x>-60&&b.x<W+60&&b.y>-60&&b.y<H+60);
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];for(let j=enemies.length-1;j>=0;j--){const e=enemies[j];if(Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e.hp-=b.damage;b.pierce--;burst(b.x,b.y,4);if(b.pierce<0)bullets.splice(i,1);if(e.hp<=0){kill(e);enemies.splice(j,1)}break}}}
for(let i=enemyBullets.length-1;i>=0;i--)if(Math.hypot(player.x-enemyBullets[i].x,player.y-enemyBullets[i].y)<player.r+enemyBullets[i].r){damagePlayer(enemyBullets[i].damage);enemyBullets.splice(i,1)}
for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.y>H+70&&!e.boss){damagePlayer(e.elite?18:8);enemies.splice(i,1)}else if(Math.hypot(player.x-e.x,player.y-e.y)<player.r+e.r){damagePlayer(e.boss?30:20);enemies.splice(i,1);burst(player.x,player.y,15,"#ff527d")}}
for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.y+=35*dt;d.life-=dt;if(Math.hypot(player.x-d.x,player.y-d.y)<player.r+d.r){if(d.type==="heal")hp=Math.min(hp+45,SHIPS.find(s=>s.id===save.selected)!.hull+save.upgrades.hull*12);if(d.type==="rapid")rapid=7;if(d.type==="shield")shieldBoost=8;if(d.type==="bomb"){for(const e of enemies)e.hp-=180;burst(player.x,player.y,70,"#d36bff")}if(d.type==="credits")save.credits+=100;persist();snd(850,.1);drops.splice(i,1)}else if(d.life<=0)drops.splice(i,1)}
for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.97;q.vy*=.97;q.life-=dt}particles=particles.filter(q=>q.life>0);
if(hp<=0)return finish(false);const done=world.kind==="survival"?time>=world.duration:world.kind==="boss"?!!world&&enemies.every(e=>!e.boss)&&spawnIndex>=world.spawns.length:world.kind==="escort"?time>=world.duration:score>=world.target;if(done)finish(true)}
function finish(win:boolean){running=false;mode="results";if(win){if(!save.completed.includes(level))save.completed.push(level);save.credits+=100+level*20;gainXP(180+level*25);save.best=Math.max(save.best,score);if(score>=1000&&!save.achievements.includes("score"))save.achievements.push("score");if(level<30)level++;persist()}overlay.classList.remove("hidden");document.body.dataset.mode="results";panel.innerHTML="<div class='brand'>"+(win?"MISSION COMPLETE":"SHIP LOST")+"</div><div class='result'>"+(win?"SECTOR SECURED":"THE FLEET HAS LOST YOUR SIGNAL")+"</div><div class='resultstats'><b>"+score.toLocaleString()+"</b> SCORE · COMBO x"+combo+"<br>"+save.credits.toLocaleString()+" CR · LV "+save.level+"</div><p>"+(win?"Rewards secured. Your progression is permanent.":"Your upgrades and credits remain safe. Refit and try again.")+"</p>";action.textContent="RETURN TO HANGAR";action.onclick=()=>renderHangar(win?"OPERATION CLEARED":"MISSION FAILED")}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88}const g=ctx.createRadialGradient(W*.5,H*.45,0,W*.5,H*.45,Math.max(W,H)*.75);g.addColorStop(0,"#0b1b3b");g.addColorStop(1,"#010207");ctx.fillStyle=g;ctx.fillRect(-20,-20,W+40,H+40);stars.forEach(s=>{ctx.globalAlpha=.3;ctx.fillStyle="#fff";ctx.fillRect(s.x,s.y,1.5,s.s/80+1)});ctx.globalAlpha=1;
for(const d of drops){ctx.fillStyle=d.type==="bomb"?"#d36bff":d.type==="heal"?"#7dffcf":d.type==="rapid"?"#ffe26b":d.type==="shield"?"#72e8ff":"#ffb347";ctx.shadowBlur=18;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,7);ctx.fill();ctx.fillStyle="#07101b";ctx.font="bold 10px system-ui";ctx.textAlign="center";ctx.fillText(d.type[0].toUpperCase(),d.x,d.y+3)}
for(const b of bullets){ctx.fillStyle=save.weapon==="plasma"?"#c779ff":"#72e8ff";ctx.shadowBlur=18;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()}for(const b of enemyBullets){ctx.fillStyle="#ff527d";ctx.shadowBlur=12;ctx.shadowColor="#ff527d";ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()}
for(const e of enemies){ctx.save();ctx.translate(e.x,e.y);ctx.shadowBlur=e.boss?35:18;ctx.shadowColor=e.boss?"#ff3f7f":e.elite?"#c779ff":e.type==="tank"?"#9d72ff":"#ffb347";ctx.fillStyle=ctx.shadowColor;ctx.beginPath();if(e.boss)ctx.arc(0,0,e.r,0,7);else{ctx.moveTo(0,e.r);ctx.lineTo(-e.r,-e.r);ctx.lineTo(0,-e.r*.35);ctx.lineTo(e.r,-e.r);ctx.closePath()}ctx.fill();ctx.restore();if(e.boss){ctx.fillStyle="#2a0b18";ctx.fillRect(e.x-90,e.y-e.r-20,180,8);ctx.fillStyle="#ff4f7d";ctx.fillRect(e.x-90,e.y-e.r-20,180*clamp(e.hp/e.max,0,1),8);ctx.fillStyle="#fff";ctx.font="bold 11px system-ui";ctx.textAlign="center";ctx.fillText(e.type+" · PHASE "+(e.phase||1),e.x,e.y-e.r-27)}}
for(const q of particles){ctx.globalAlpha=clamp(q.life*2,0,1);if(q.size>10){ctx.fillStyle="#fff";ctx.font="900 "+q.size+"px system-ui";ctx.textAlign="center";ctx.fillText(q.text,q.x,q.y)}else{ctx.fillStyle=q.text;ctx.fillRect(q.x,q.y,q.size,q.size)}}ctx.globalAlpha=1;ctx.shadowBlur=22;ctx.shadowColor="#5de4ff";ctx.fillStyle=flash>0?"#fff":"#5de4ff";ctx.beginPath();ctx.moveTo(player.x,player.y-28);ctx.lineTo(player.x-22,player.y+22);ctx.lineTo(player.x,player.y+13);ctx.lineTo(player.x+22,player.y+22);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#d8ecff";ctx.font="900 12px system-ui";ctx.textAlign="left";ctx.fillText(world.name+" · "+world.kind.toUpperCase()+" · SCORE "+score+" · COMBO x"+combo,18,25);ctx.fillText("HULL "+Math.max(0,Math.ceil(hp))+" · CR "+save.credits+" · "+save.weapon.toUpperCase(),18,H-20);if(world.kind==="survival"){ctx.textAlign="right";ctx.fillText("TIME "+Math.max(0,Math.ceil(world.duration-time))+"s",W-18,25)}ctx.restore()}
function loop(t:number){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
function pauseGame(){if(mode!=="game")return;mode="pause";running=false;overlay.classList.remove("hidden");panel.innerHTML="<div class='brand'>PAUSED</div><div class='result'>MISSION IN PROGRESS</div><p>Your run is frozen.</p>";action.textContent="RESUME";action.onclick=()=>{mode="game";overlay.classList.add("hidden");running=true;last=performance.now();requestAnimationFrame(loop)}}
function setupTouch(){if(touchReady)return;touchReady=true;const root=document.querySelector("#game")!,ui=document.createElement("div");ui.className="touch";ui.innerHTML="<div class='joystick'><i></i></div><button class='touch-dash'>DASH</button><button class='touch-fire'>FIRE</button><button class='touch-pause'>Ⅱ</button>";root.append(ui);const joy=ui.querySelector<HTMLElement>(".joystick")!,knob=joy.querySelector<HTMLElement>("i")!;let active=false;joy.onpointerdown=e=>{active=true;joy.setPointerCapture(e.pointerId)};joy.onpointermove=e=>{if(!active)return;const r=joy.getBoundingClientRect(),dx=clamp((e.clientX-r.left-r.width/2)/45,-1,1),dy=clamp((e.clientY-r.top-r.height/2)/45,-1,1);touch.x=dx;touch.y=dy;knob.style.transform="translate("+(dx*38)+"px,"+(dy*38)+"px)"};const end=()=>{active=false;touch.x=0;touch.y=0;knob.style.transform="translate(0,0)"};joy.onpointerup=end;joy.onpointercancel=end;const f=ui.querySelector(".touch-fire")!;f.addEventListener("pointerdown",()=>touch.fire=true);f.addEventListener("pointerup",()=>touch.fire=false);f.addEventListener("pointercancel",()=>touch.fire=false);ui.querySelector(".touch-dash")!.addEventListener("pointerdown",dashNow);ui.querySelector(".touch-pause")!.addEventListener("pointerdown",pauseGame)}
addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.code==="Space")e.preventDefault();if(e.key==="Shift")dashNow();if(e.key==="Escape")pauseGame()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));addEventListener("resize",resize);resize();setupTouch();renderHangar();
