import { generateLevel, type GeneratedLevel } from "./levels";

type ShipId="viper"|"nova"|"titan"; type WeaponId="pulse"|"twin"|"plasma"|"rail"; type UpgradeKey="damage"|"fireRate"|"shield"|"hull";
type Save={credits:number,xp:number,level:number,selected:ShipId,ships:Record<ShipId,boolean>,upgrades:Record<UpgradeKey,number>,weapon:WeaponId,completed:number[],best:number};
type E={x:number,y:number,r:number,hp:number,max:number,type:string,t:number,shoot:number,[k:string]:any};
const C=document.querySelector<HTMLCanvasElement>("#canvas")!,X=C.getContext("2d")!,O=document.querySelector("#overlay")!,M=document.querySelector("#message")!,A=document.querySelector<HTMLButtonElement>("#action")!;
const KEY="interstella-save-v4",ships=[{id:"viper" as ShipId,name:"Viper",speed:470,hull:90,price:0,unlock:1},{id:"nova" as ShipId,name:"Nova",speed:395,hull:125,price:900,unlock:3},{id:"titan" as ShipId,name:"Titan",speed:330,hull:175,price:1800,unlock:6}],weapons=[{id:"pulse" as WeaponId,name:"Pulse",cool:.16,damage:1,price:0,unlock:1},{id:"twin" as WeaponId,name:"Twin Laser",cool:.2,damage:1,price:600,unlock:2},{id:"plasma" as WeaponId,name:"Plasma",cool:.34,damage:3.5,price:1200,unlock:4},{id:"rail" as WeaponId,name:"Rail Cannon",cool:.55,damage:8,price:2400,unlock:7}];
const fresh=():Save=>({credits:0,xp:0,level:1,selected:"viper",ships:{viper:true,nova:false,titan:false},upgrades:{damage:1,fireRate:1,shield:0,hull:0},weapon:"pulse",completed:[],best:0});let save=fresh();try{save={...save,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}
let combo=0,comboTimer=0,dash=0,dashCooldown=0,powerups:E[]=[],level=1,world:GeneratedLevel=generateLevel(1),W=0,H=0,running=false,last=0,time=0,spawnAt=0,score=0,hp=100,shots:E[]=[],enemyShots:E[]=[],enemies:E[]=[],particles:E[]=[],stars:E[]=[],keys=new Set<string>(),audio:AudioContext|null=null,shake=0,boost=0;
let ws:WebSocket|null=null,online=false,peers=new Map<string,any>(),liberation=0;
const p={x:0,y:0,r:18,cool:0};
const xpNeed=()=>Math.floor(250*Math.pow(save.level,1.45));const persist=()=>localStorage.setItem(KEY,JSON.stringify(save));
function xp(n:number){save.xp+=n;while(save.level<20&&save.xp>=xpNeed()){save.xp-=xpNeed();save.level++;burst(p.x,p.y,30,"#7dffcf")}persist()}
function rng(seed:number){let s=seed>>>0;return()=>{s=(Math.imul(s^s>>>16,2246822519)+3266489917)>>>0;return(s>>>0)/4294967296}}
function resize(){W=innerWidth;H=innerHeight;const d=devicePixelRatio||1;C.width=W*d;C.height=H*d;X.setTransform(d,0,0,d,0,0);p.x=Math.min(Math.max(p.x,25),W-25)||W/2;p.y=Math.min(Math.max(p.y,45),H-45)||H-80;const r=rng(world.seed);stars=Array.from({length:Math.min(220,Math.floor(W*H/6000))},()=>({x:r()*W,y:r()*H,r:1+2*r(),hp:25+150*r(),max:0,type:"star",t:0,shoot:0}))}
function snd(f:number,d=.05){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.02;g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function burst(x:number,y:number,n=20,col="#72e8ff"){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*280;particles.push({x,y,r:1+Math.random()*4,hp:s,max:.25+.5*Math.random(),type:col,t:0,shoot:0})}shake=Math.min(18,shake+n*.08)}
function show(){world=generateLevel(level);running=false;O.classList.remove("hidden");document.body.dataset.mode="hangar";A.textContent="LAUNCH";const s=ships.find(v=>v.id===save.selected)!,w=weapons.find(v=>v.id===save.weapon)!;M.innerHTML=`<div class="hangar-title">INTERSTELLA</div><div class="subtitle">${online?"ONLINE SQUAD":"SOLO COMMAND"}</div><div class="stats"><b>LV ${save.level}</b> · ${save.xp}/${xpNeed()} XP · <b>${save.credits} CR</b> · ${save.completed.length} CLEARED</div><div class="xp"><i style="width:${Math.min(100,save.xp/xpNeed()*100)}%"></i></div><div class="missioncard"><b>${world.name}</b><br>${world.kind.toUpperCase()} · SEED ${world.seed}<br><small>Generated once from this seed. Replay gives the same enemy wave sequence.</small></div><div class="shipcard"><b>${s.name}</b><span>HULL ${s.hull+save.upgrades.hull*12} · SPEED ${s.speed}</span></div><div class="actions"><button id="prev">◀ LEVEL</button><button id="next">LEVEL ▶</button><button id="net">${online?"DISCONNECT":"ONLINE SQUAD"}</button><button id="dmg">DAMAGE +${save.upgrades.damage}</button><button id="fir">FIRE +${save.upgrades.fireRate}</button><button id="sh">SHIELD +${save.upgrades.shield}</button><button id="hu">HULL +${save.upgrades.hull}</button><button id="ship">SHIP</button><button id="weapon">WEAPON</button></div><div class="loadout">${w.name} · ROOM ${online?"CONNECTED":"OFFLINE"}</div>${online?`<div class="note">SQUAD ${peers.size+1}/4 · LIBERATION ${Math.round(liberation)}%</div>`:""}`;document.querySelector("#prev")?.addEventListener("click",()=>{level=Math.max(1,level-1);show()});document.querySelector("#next")?.addEventListener("click",()=>{level=Math.min(30,level+1);show()});document.querySelector("#net")?.addEventListener("click",()=>online?disconnect():connect());document.querySelector("#dmg")?.addEventListener("click",()=>buy("damage"));document.querySelector("#fir")?.addEventListener("click",()=>buy("fireRate"));document.querySelector("#sh")?.addEventListener("click",()=>buy("shield"));document.querySelector("#hu")?.addEventListener("click",()=>buy("hull"));document.querySelector("#ship")?.addEventListener("click",cycleShip);document.querySelector("#weapon")?.addEventListener("click",cycleWeapon);A.onclick=launch;portrait()}
function buy(k:UpgradeKey){const c=180+save.upgrades[k]*170+save.level*25;if(save.upgrades[k]>=8)return show();if(save.credits<c)return show();save.credits-=c;save.upgrades[k]++;persist();show()}
function cycleShip(){const i=ships.findIndex(s=>s.id===save.selected),s=ships[(i+1)%ships.length];if(save.level<s.unlock)return; if(!save.ships[s.id]){if(save.credits<s.price)return;save.credits-=s.price;save.ships[s.id]=true}save.selected=s.id;persist();show()}
function cycleWeapon(){const i=weapons.findIndex(w=>w.id===save.weapon),w=weapons[(i+1)%weapons.length];if(save.level<w.unlock)return;if(save.credits<w.price&&!save.completed.length)return;save.credits=Math.max(0,save.credits-w.price);save.weapon=w.id;persist();show()}
function connect(){const url=(import.meta as any).env?.VITE_WS_URL||`ws://${location.hostname}:8080`;ws=new WebSocket(url);ws.onopen=()=>ws!.send(JSON.stringify({type:"join",room:`level-${level}`,name:`Pilot-${Math.floor(Math.random()*9999)}`}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="joined"){online=true;liberation=m.liberation||0;(m.players||[]).forEach((q:any)=>peers.set(q.id,q));show()}else if(m.type==="player_join")peers.set(m.player.id,m.player);else if(m.type==="player_state")peers.set(m.player.id,m.player);else if(m.type==="player_leave")peers.delete(m.id);else if(m.type==="liberation")liberation=m.value};ws.onclose=()=>{online=false;peers.clear();ws=null;show()};ws.onerror=()=>show()}
function disconnect(){ws?.close();online=false;peers.clear();show()}function net(type:string,data:any={}){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type,...data}))}
function addPowerup(x:number,y:number){if(Math.random()<.12)powerups.push({x,y,r:12,hp:1,max:7,type:["heal","rapid","shield","bomb"][Math.floor(Math.random()*4)],t:0,shoot:0})}
function launch(){audio??=new AudioContext();audio.resume();world=generateLevel(level);running=true;O.classList.add("hidden");document.body.dataset.mode="game";time=0;spawnAt=0;score=0;hp=ships.find(s=>s.id===save.selected)!.hull+save.upgrades.hull*12;shots=[];enemyShots=[];enemies=[];particles=[];last=performance.now();requestAnimationFrame(loop)}
function fire(){if(p.cool>0)return;const w=weapons.find(v=>v.id===save.weapon)!,d=w.damage*(1+save.upgrades.damage*.18);const o=save.weapon==="twin"?[-12,12]:[0];o.forEach(x=>shots.push({x:p.x+x,y:p.y-25,r:save.weapon==="plasma"?8:5,hp:d,max:w.cool,v:save.weapon==="rail"?980:760,type:"shot",t:0,shoot:0}));p.cool=w.cool/Math.sqrt(save.upgrades.fireRate);snd(save.weapon==="rail"?100:600,.035)}
function spawnEnemy(q:any){const hp=(q.kind==="tank"?7:q.kind==="elite"?13:q.kind==="swarmer"?.8:1)*(1+level*.04);enemies.push({x:q.x*W,y:-35,r:q.kind==="tank"?28:q.kind==="elite"?24:q.kind==="swarmer"?11:17,hp,max:hp,type:q.kind,t:0,shoot:1+Math.random()*1.5})}
function update(dt:number){
dashCooldown=Math.max(0,dashCooldown-dt); dash=Math.max(0,dash-dt); comboTimer-=dt; if(comboTimer<=0)combo=0;let dx=(keys.has("a")||keys.has("arrowleft")?-1:0)+(keys.has("d")||keys.has("arrowright")?1:0),dy=(keys.has("w")||keys.has("arrowup")?-1:0)+(keys.has("s")||keys.has("arrowdown")?1:0),l=Math.hypot(dx,dy)||1;const ship=ships.find(s=>s.id===save.selected)!;p.x=Math.max(25,Math.min(W-25,p.x+dx/l*ship.speed*dt*(dash>0?3.2:boost>0?1.6:1)));p.y=Math.max(45,Math.min(H-45,p.y+dy/l*ship.speed*dt*(dash>0?3.2:boost>0?1.6:1)));if(keys.has(" ")||keys.has("space"))fire(); if(keys.has("shift")&&dashCooldown<=0){dash=.18;dashCooldown=1.2;snd(900,.06)}if(keys.has("shift")&&boost<=0)boost=.8;boost=Math.max(0,boost-dt);p.cool=Math.max(0,p.cool-dt);time+=dt;while(spawnAt<world.spawns.length&&world.spawns[spawnAt].t<=time)spawnEnemy(world.spawns[spawnAt++]);stars.forEach(s=>{s.y+=s.hp*dt*(boost>0?3:1);if(s.y>H)s.y=0});shots.forEach(s=>s.y-=s.v*dt);shots=shots.filter(s=>s.y>-50);enemyShots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt});enemyShots=enemyShots.filter(s=>s.x>-50&&s.x<W+50&&s.y>-50&&s.y<H+50);enemies.forEach(e=>{e.y+=(70+level*6+(e.type==="elite"?35:0))*dt;e.t+=dt;if(e.type==="zig")e.x+=Math.sin(e.t*3)*80*dt;if(e.type==="swarmer")e.x+=Math.sin(e.t*7)*130*dt;e.shoot-=dt;if(e.shoot<=0){const a=Math.atan2(p.y-e.y,p.x-e.x);enemyShots.push({x:e.x,y:e.y,r:5,hp:0,max:0,vx:Math.cos(a)*(160+level*4),vy:Math.sin(a)*(160+level*4),type:"enemy",t:0,shoot:0});e.shoot=1.5+Math.random()*2}});for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];for(let j=shots.length-1;j>=0;j--)if(Math.hypot(e.x-shots[j].x,e.y-shots[j].y)<e.r+shots[j].r){e.hp-=shots[j].hp;shots.splice(j,1);burst(e.x,e.y,5);if(e.hp<=0){const reward=e.type==="elite"?70:e.type==="tank"?30:15;score+=reward;save.credits+=reward;combo++;comboTimer=3;save.credits+=Math.floor(reward*Math.min(combo,10)*.05);addPowerup(e.x,e.y);xp(e.type==="elite"?55:10);if(online)net("liberate",{amount:e.type==="elite"?4:1});burst(e.x,e.y,e.type==="elite"?35:18,e.type==="elite"?"#ff3f7f":"#ffb347");enemies.splice(i,1);break}}if(enemies[i]&&Math.hypot(p.x-e.x,p.y-e.y)<p.r+e.r){hp-=20;enemies.splice(i,1);shake=8}}for(let i=enemyShots.length-1;i>=0;i--)if(Math.hypot(p.x-enemyShots[i].x,p.y-enemyShots[i].y)<p.r+enemyShots[i].r){hp-=10;enemyShots.splice(i,1);shake=7}net("state",{x:p.x/W,y:p.y/H,hp});const done=world.kind==="survival"?time>=world.duration:world.kind==="boss"?time>=world.duration&&!enemies.length:(online?liberation>=100:score>=world.target);if(done){if(!save.completed.includes(level))save.completed.push(level);save.credits+=100+level*15;xp(200+level*30);save.best=Math.max(save.best,score);persist();show()}if(hp<=0){running=false;show()}}
function draw(){X.clearRect(0,0,W,H);X.save();if(shake){X.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88}stars.forEach(s=>{X.globalAlpha=.3+s.r*.2;X.fillStyle="#fff";X.fillRect(s.x,s.y,s.r,s.r*2)});X.globalAlpha=1;shots.forEach(s=>{X.fillStyle="#72e8ff";X.shadowBlur=18;X.shadowColor="#72e8ff";X.beginPath();X.arc(s.x,s.y,s.r,0,7);X.fill()});enemyShots.forEach(s=>{X.fillStyle="#ff527d";X.beginPath();X.arc(s.x,s.y,s.r,0,7);X.fill()});enemies.forEach(e=>{X.fillStyle=e.type==="elite"?"#ff3f7f":e.type==="tank"?"#b879ff":"#ffb347";X.shadowBlur=20;X.shadowColor=X.fillStyle;X.beginPath();X.moveTo(e.x,e.y+e.r);X.lineTo(e.x-e.r,e.y-e.r);X.lineTo(e.x,e.y-e.r*.3);X.lineTo(e.x+e.r,e.y-e.r);X.closePath();X.fill()});peers.forEach(q=>{X.fillStyle="#7dffcf";X.beginPath();X.arc(q.x*W,q.y*H,12,0,7);X.fill()});particles.forEach(q=>{X.globalAlpha=Math.max(0,q.max*2);X.fillStyle=q.type;X.fillRect(q.x,q.y,q.r,q.r);q.x+=q.hp/60;q.y+=q.hp/60;q.max-=.016});X.globalAlpha=1;X.shadowBlur=20;X.shadowColor="#5de4ff";X.fillStyle="#5de4ff";X.beginPath();X.moveTo(p.x,p.y-27);X.lineTo(p.x-21,p.y+21);X.lineTo(p.x,p.y+13);X.lineTo(p.x+21,p.y+21);X.closePath();X.fill();X.shadowBlur=0;X.fillStyle="#b9d8ff";X.font="12px system-ui";X.fillText(`${world.name} · COMBO x${combo} · ${online?`LIBERATION ${Math.round(liberation)}% · `:""}SCORE ${score} · HULL ${Math.max(0,Math.ceil(hp))} · CR ${save.credits}`,18,H-18);X.restore()}
function loop(t:number){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
function portrait(){let n=document.querySelector(".rotate-notice") as HTMLElement|null;if(!n){n=document.createElement("div");n.className="rotate-notice";n.textContent="ROTATE TO LANDSCAPE FOR COMBAT";document.querySelector("#game")!.append(n)}n.classList.toggle("show",innerWidth<innerHeight)}
function touch(){
if(document.querySelector(".touchpad"))return;const e=document.createElement("div");e.className="touchpad";e.innerHTML=`<div class="stick"><span></span></div><button class="touchfire">FIRE</button>`;document.querySelector("#game")!.append(e);const st=e.querySelector<HTMLElement>(".stick")!,kn=st.querySelector<HTMLElement>("span")!,fb=e.querySelector<HTMLButtonElement>(".touchfire")!;let on=false;st.onpointerdown=ev=>{on=true;st.setPointerCapture(ev.pointerId)};st.onpointermove=ev=>{if(!on)return;const r=st.getBoundingClientRect(),dx=Math.max(-42,Math.min(42,ev.clientX-r.left-r.width/2)),dy=Math.max(-42,Math.min(42,ev.clientY-r.top-r.height/2));kn.style.transform=`translate(${dx}px,${dy}px)`;["a","d","w","s"].forEach(k=>keys.delete(k));if(dx<-8)keys.add("a");if(dx>8)keys.add("d");if(dy<-8)keys.add("w");if(dy>8)keys.add("s")};const end=()=>{on=false;kn.style.transform="translate(0,0)";["a","d","w","s"].forEach(k=>keys.delete(k))};st.onpointerup=end;st.onpointercancel=end;fb.onpointerdown=()=>keys.add(" ");fb.onpointerup=()=>keys.delete(" ")}
addEventListener("resize",()=>{resize();portrait()});addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.code==="Space")e.preventDefault()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));resize();touch();show();
