import * as THREE from "three";
import "../space3d.css";

type ShipId = "viper" | "nova" | "titan";
type EnemyKind = "fighter" | "swarmer" | "tank" | "elite" | "shielded" | "boss";
type Save = { mission:number; credits:number; xp:number; level:number; hull:number; weapon:number; shield:number; selected:ShipId; unlocked:ShipId[]; secrets:number[] };
const KEY="interstella-v3-save";
const SHIPS:Record<ShipId,{speed:number;hull:number;damage:number;color:number;cooldown:number}>={viper:{speed:24,hull:90,damage:18,color:0x42dcff,cooldown:.16},nova:{speed:19,hull:120,damage:25,color:0xb875ff,cooldown:.22},titan:{speed:13,hull:190,damage:38,color:0xffa640,cooldown:.34}};
let save:Save=load(); let running=false,paused=false,time=0,score=0,combo=0,comboTimer=0,hp=SHIPS[save.selected].hull+save.hull*10,ability=0,fireHeld=false;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x01030a); scene.fog=new THREE.FogExp2(0x01030a,.012);
const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,1600);camera.position.set(0,6,18);camera.lookAt(0,0,-80);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.domElement.id="interstella3d";document.body.appendChild(renderer.domElement);
const world=new THREE.Group();scene.add(world); const player=new THREE.Group();scene.add(player); const enemies:THREE.Group[]=[]; const bullets:THREE.Mesh[]=[]; const enemyBullets:THREE.Mesh[]=[]; const asteroids:THREE.Mesh[]=[]; const particles:THREE.Mesh[]=[];
function load():Save{try{return {...{mission:1,credits:0,xp:0,level:1,hull:0,weapon:0,shield:0,selected:"viper",unlocked:["viper"],secrets:[]},...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return {mission:1,credits:0,xp:0,level:1,hull:0,weapon:0,shield:0,selected:"viper",unlocked:["viper"],secrets:[]}}}
function persist(){localStorage.setItem(KEY,JSON.stringify(save))}
function meshShip(color:number,scale=1){const g=new THREE.Group();const mat=new THREE.MeshBasicMaterial({color,wireframe:false});const dark=new THREE.MeshBasicMaterial({color:0x061321});const body=new THREE.Mesh(new THREE.ConeGeometry(1.15*scale,4.2*scale,5),mat);body.rotation.x=Math.PI/2;g.add(body);const wings=new THREE.Mesh(new THREE.BoxGeometry(4.4*scale,.18*scale,1.3*scale),mat);g.add(wings);const core=new THREE.Mesh(new THREE.SphereGeometry(.45*scale,8,8),dark);core.position.z=1.15*scale;g.add(core);return g}
player.add(meshShip(SHIPS[save.selected].color));player.position.set(0,-2,5);
function addStars(){const geo=new THREE.BufferGeometry();const p=new Float32Array(1800);for(let i=0;i<p.length;i+=3){p[i]=(Math.random()-.5)*650;p[i+1]=(Math.random()-.5)*360;p[i+2]=-Math.random()*1400}geo.setAttribute("position",new THREE.BufferAttribute(p,3));scene.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0xd8f2ff,size:1,sizeAttenuation:true})))}
function makeAsteroids(){for(let i=0;i<45;i++){const a=new THREE.Mesh(new THREE.IcosahedronGeometry(1.5+Math.random()*5,1),new THREE.MeshBasicMaterial({color:0x655b55,wireframe:true}));a.position.set((Math.random()-.5)*180,(Math.random()-.5)*80,-40-Math.random()*700);a.userData.v=12+Math.random()*22;a.userData.r=a.geometry.boundingSphere?.radius||3;world.add(a);asteroids.push(a)}}
function spawnEnemy(kind:EnemyKind,x:number,z=-100){const colors:Record<EnemyKind,number>={fighter:0xff596f,swarmer:0xffb43b,tank:0x9b6cff,elite:0x55f2c4,shielded:0x53c9ff,boss:0xff315f};const g=meshShip(colors[kind],kind==="boss"?3.8:kind==="tank"?1.7:1);g.position.set(x,(Math.random()-.5)*5,z);g.userData={kind,hp:kind==="boss"?1500:kind==="tank"?180:kind==="elite"?100:kind==="shielded"?80:45,max:kind==="boss"?1500:kind==="tank"?180:kind==="elite"?100:kind==="shielded"?80:45,cool:Math.random()+.4,shield:kind==="shielded"?70:0,phase:1};world.add(g);enemies.push(g);return g}
function clearGroup(arr:THREE.Object3D[]){for(const o of arr)world.remove(o);arr.length=0}
function launch(){running=true;paused=false;time=0;score=0;combo=0;comboTimer=0;hp=SHIPS[save.selected].hull+save.hull*10;ability=0;clearGroup(enemies);clearGroup(bullets);clearGroup(enemyBullets);for(let i=0;i<10+Math.min(save.mission,20);i++)spawnEnemy(i%3===0?"swarmer":i%7===0?"elite":"fighter",(Math.random()-.5)*30,-90-i*28);if(save.mission%5===0||save.mission===30)spawnEnemy(save.mission===30?"boss":"tank",0,-330);ui.classList.add("hidden");}
function shoot(){if(!running||paused)return;const s=SHIPS[save.selected];const b=new THREE.Mesh(new THREE.SphereGeometry(.14,6,6),new THREE.MeshBasicMaterial({color:0x7cecff}));b.position.copy(player.position);b.userData={v:-70,damage:s.damage+save.weapon*7,life:4};world.add(b);bullets.push(b)}
function burst(pos:THREE.Vector3,color=0xffc85c,n=12){for(let i=0;i<n;i++){const p=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.12),new THREE.MeshBasicMaterial({color}));p.position.copy(pos);p.userData={life:.5+Math.random()*.6,v:new THREE.Vector3((Math.random()-.5)*18,(Math.random()-.5)*18,(Math.random()-.5)*18)};world.add(p);particles.push(p)}}
function enemyFire(e:THREE.Group){const b=new THREE.Mesh(new THREE.SphereGeometry(e.userData.kind==="boss"?.28:.13,6,6),new THREE.MeshBasicMaterial({color:0xff547c}));b.position.copy(e.position);const v=player.position.clone().sub(e.position).normalize().multiplyScalar(e.userData.kind==="boss"?20:15);b.userData={v,life:7};world.add(b);enemyBullets.push(b)}
function destroyEnemy(i:number){const e=enemies[i];burst(e.position,e.userData.kind==="boss"?0xff3d8d:0xff9e52,e.userData.kind==="boss"?70:18);score+=e.userData.kind==="boss"?5000:100;combo++;comboTimer=2.5;save.credits+=e.userData.kind==="boss"?1200:15;save.xp+=e.userData.kind==="boss"?900:35;world.remove(e);enemies.splice(i,1);if(save.xp>=save.level*1000){save.level++;save.xp=0}persist()}
function damage(n:number){hp-=Math.max(1,n-save.shield*2);burst(player.position,0xff426f,6);if(hp<=0){running=false;show("MISSION FAILED","The fleet needs you. Upgrade your ship and try again.")}}
function complete(){running=false;save.mission=Math.min(30,save.mission+1);save.credits+=300;save.xp+=250;const unlocked=save.mission===11?"nova":save.mission===21?"titan":null;if(unlocked&&!save.unlocked.includes(unlocked))save.unlocked.push(unlocked);persist();show(save.mission===30?"CAMPAIGN COMPLETE":"MISSION COMPLETE",`Score ${score}  •  Credits +300  •  Level ${save.level}`)}
function show(title:string,text:string){ui.classList.remove("hidden");titleEl.textContent=title;textEl.textContent=text;action.textContent=running?"RESUME":"LAUNCH MISSION"}
function update(dt:number){if(!running||paused)return;time+=dt;const s=SHIPS[save.selected];let ax=input.x,ay=input.y;player.position.x=THREE.MathUtils.clamp(player.position.x+ax*s.speed*dt,-28,28);player.position.y=THREE.MathUtils.clamp(player.position.y+ay*s.speed*dt,-11,9);player.rotation.z+=(ax*.22-player.rotation.z)*.15;ability=Math.max(0,ability-dt);if(fireHeld)shoot();
for(const a of asteroids){a.position.z+=a.userData.v*dt;if(a.position.z>30)a.position.z=-750-Math.random()*300;if(a.position.distanceTo(player.position)<3.2)damage(10)}
for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];const k=e.userData.kind;e.position.z+=dt*(k==="swarmer"?11:k==="boss"?5:7);if(k==="fighter"||k==="elite")e.position.x+=Math.sin(time*2+e.id)*dt*5;if(k==="boss"){e.userData.phase=e.userData.hp<1000?2:1;e.position.x=Math.sin(time*.65)*18;if(e.userData.phase===2)e.rotation.z=Math.sin(time*2)*.2}e.userData.cool-=dt;if(e.userData.cool<=0){enemyFire(e);e.userData.cool=k==="boss"?.55:1.3+Math.random()*1.5}if(e.userData.shield>0)e.userData.shield=Math.min(70,e.userData.shield+dt*3);if(e.position.z>18){damage(k==="boss"?30:8);world.remove(e);enemies.splice(i,1)}}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.position.z+=b.userData.v*dt;b.userData.life-=dt;let hit=false;for(let j=enemies.length-1;j>=0;j--){const e=enemies[j];if(b.position.distanceTo(e.position)<(e.userData.kind==="boss"?8:2.2)){let d=b.userData.damage;if(e.userData.shield>0){const a=Math.min(e.userData.shield,d);e.userData.shield-=a;d-=a}e.userData.hp-=d;burst(b.position,d>30?0xfff06a:0x62eaff,5);hit=true;if(e.userData.hp<=0)destroyEnemy(j);break}}if(hit||b.userData.life<=0){world.remove(b);bullets.splice(i,1)}}
for(let i=enemyBullets.length-1;i>=0;i--){const b=enemyBullets[i];b.position.addScaledVector(b.userData.v,dt);b.userData.life-=dt;if(b.position.distanceTo(player.position)<1.8){damage(12);world.remove(b);enemyBullets.splice(i,1)}else if(b.userData.life<=0){world.remove(b);enemyBullets.splice(i,1)}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.position.addScaledVector(p.userData.v,dt);p.userData.life-=dt;if(p.userData.life<=0){world.remove(p);particles.splice(i,1)}}
if(enemies.length===0)complete();hud.textContent=`MISSION ${save.mission}  •  SCORE ${score}  •  COMBO x${combo}  •  HULL ${Math.max(0,Math.ceil(hp))}`;abilityEl.textContent=ability<=0?"ABILITY READY":"ABILITY "+Math.ceil(ability)+"s";}
function loop(now:number){requestAnimationFrame(loop);const dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt);renderer.render(scene,camera)}let last=performance.now();
const ui=document.createElement("section");ui.id="menu";ui.innerHTML=`<div class="menu-card"><div class="logo">INTERSTELLA</div><div id="title">3D SPACE COMBAT</div><p id="desc">Campaign ${save.mission}/30 • Credits ${save.credits} • Level ${save.level}</p><button id="launch">LAUNCH MISSION</button><div class="ships"><button data-ship="viper">VIPER</button><button data-ship="nova">NOVA</button><button data-ship="titan">TITAN</button></div></div>`;document.body.appendChild(ui);const titleEl=ui.querySelector("#title") as HTMLElement,textEl=ui.querySelector("#desc") as HTMLElement,action=ui.querySelector("#launch") as HTMLButtonElement,hud=document.createElement("div");hud.id="hud3d";document.body.appendChild(hud);const abilityEl=document.createElement("div");abilityEl.id="ability";document.body.appendChild(abilityEl);action.onclick=()=>{if(running){paused=!paused;action.textContent=paused?"RESUME":"PAUSE"}else launch()};ui.querySelectorAll<HTMLButtonElement>("[data-ship]").forEach(b=>b.onclick=()=>{const id=b.dataset.ship as ShipId;if(save.unlocked.includes(id)){save.selected=id;player.clear();player.add(meshShip(SHIPS[id].color));persist();textEl.textContent=`${id.toUpperCase()} selected • Campaign ${save.mission}/30`}});
const input={x:0,y:0};function touchMove(e:PointerEvent){input.x=THREE.MathUtils.clamp((e.clientX-innerWidth/2)/(innerWidth/2),-1,1);input.y=THREE.MathUtils.clamp(-(e.clientY-innerHeight/2)/(innerHeight/2),-1,1)}renderer.domElement.addEventListener("pointermove",e=>{if(e.buttons)touchMove(e)});renderer.domElement.addEventListener("pointerdown",e=>{fireHeld=true;touchMove(e)});addEventListener("pointerup",()=>{fireHeld=false;input.x=0;input.y=0});addEventListener("keydown",e=>{if(e.code==="Space")fireHeld=true;if(e.key.toLowerCase()==="e"&&ability<=0){ability=save.selected==="viper"?1.2:save.selected==="nova"?8:12;burst(player.position,0x8ceeff,25)}});addEventListener("keyup",e=>{if(e.code==="Space")fireHeld=false});addStars();makeAsteroids();
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});requestAnimationFrame(loop);