type ShipId="viper"|"nova"|"titan"; type WeaponId="pulse"|"twin"|"plasma";
type Save={credits:number,selected:ShipId,ships:Record<ShipId,boolean>,upgrades:{damage:number,fireRate:number,shield:number},weapon:WeaponId,missions:number[],best:number};
const C=document.querySelector<HTMLCanvasElement>("#canvas")!,X=C.getContext("2d")!,O=document.querySelector("#overlay")!,M=document.querySelector("#message")!,A=document.querySelector<HTMLButtonElement>("#action")!;
const KEY="interstella-save-v1",ships=[{id:"viper" as ShipId,name:"Viper",speed:390,hull:85,price:0},{id:"nova" as ShipId,name:"Nova",speed:330,hull:110,price:900},{id:"titan" as ShipId,name:"Titan",speed:280,hull:145,price:1600}],weapons=[{id:"pulse" as WeaponId,name:"Pulse",cool:.18,damage:1},{id:"twin" as WeaponId,name:"Twin Laser",cool:.22,damage:1},{id:"plasma" as WeaponId,name:"Plasma",cool:.34,damage:3}],missions=[["Outer Orbit","Score 500","score",500],["Red Nebula","Survive 45 seconds","survive",45],["Iron Gate","Destroy the mini-boss","boss",1],["Deep Space","Score 1800","score",1800],["Interstellar Core","Defeat the final boss","boss",1]] as const;
const fresh=():Save=>({credits:0,selected:"viper",ships:{viper:true,nova:false,titan:false},upgrades:{damage:1,fireRate:1,shield:0},weapon:"pulse",missions:[],best:0});
let save:Save;try{save={...fresh(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{save=fresh()}
let W=0,H=0,mode:"hangar"|"game"="hangar",mission=0,running=false,last=0,time=0,spawn=0,bossSpawned=false,score=0,health=100,shots:any[]=[],enemyShots:any[]=[],enemies:any[]=[],particles:any[]=[],stars:any[]=[],keys=new Set<string>(),audio:AudioContext|null=null,objective=0;
const p={x:0,y:0,r:18,cool:0};
function saveIt(){localStorage.setItem(KEY,JSON.stringify(save))}
function resize(){W=innerWidth;H=innerHeight;const d=devicePixelRatio||1;C.width=W*d;C.height=H*d;X.setTransform(d,0,0,d,0,0);p.x=W/2;p.y=H-90;stars=Array.from({length:140},()=>({x:Math.random()*W,y:Math.random()*H,s:20+Math.random()*120,z:1+Math.random()*2}))}
function snd(f:number,d=.05){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.025;g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function showHangar(note=""){mode="hangar";running=false;O.classList.remove("hidden");A.textContent="LAUNCH MISSION";M.innerHTML="<b>HANGAR</b><br><small>Credits: "+save.credits+" · Ship: "+ships.find(s=>s.id===save.selected)!.name+" · Weapon: "+save.weapon+"</small><br><br>"+note+"<br><br><b>MISSION "+Math.min(mission+1,missions.length)+"/"+missions.length+"</b><br>"+(missions[mission]?.[1]||"Campaign complete!")+"<br><br><button id='damage'>UPGRADE DAMAGE</button> <button id='shield'>UPGRADE SHIELD</button><br><button id='ship'>SHIP / BUY</button> <button id='weapon'>CHANGE WEAPON</button>"; document.querySelector("#damage")?.addEventListener("click",()=>buy("damage"));document.querySelector("#shield")?.addEventListener("click",()=>buy("shield"));document.querySelector("#ship")?.addEventListener("click",cycleShip);document.querySelector("#weapon")?.addEventListener("click",cycleWeapon)}
function buy(k:"damage"|"shield"){const price=k==="damage"?150+save.upgrades.damage*150:200+save.upgrades.shield*200;if(save.credits>=price&&save.upgrades[k]<6){save.credits-=price;save.upgrades[k]++;saveIt();showHangar("Upgrade installed.")}}
function cycleShip(){const i=ships.findIndex(s=>s.id===save.selected),n=ships[(i+1)%ships.length];if(!save.ships[n.id]){if(save.credits<n.price)return;save.credits-=n.price;save.ships[n.id]=true}save.selected=n.id;saveIt();showHangar(n.name+" selected.")}
function cycleWeapon(){const i=weapons.findIndex(w=>w.id===save.weapon);save.weapon=weapons[(i+1)%weapons.length].id;saveIt();showHangar("Weapon changed.")}
function launch(){audio??=new AudioContext();audio.resume();mode="game";O.classList.add("hidden");running=true;time=0;score=0;objective=0;health=ships.find(s=>s.id===save.selected)!.hull;shots=[];enemyShots=[];enemies=[];particles=[];spawn=.5;bossSpawned=false;last=performance.now();snd(220,.18);requestAnimationFrame(loop)}
function burst(x:number,y:number,n=20,col="#72e8ff"){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*230;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.5,size:2+Math.random()*4,col})}}
function hit(a:any,b:any){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r}
function fire(){if(p.cool>0)return;const w=weapons.find(v=>v.id===save.weapon)!;const offs=save.weapon==="twin"?[-11,11]:[0];offs.forEach(o=>shots.push({x:p.x+o,y:p.y-22,r:save.weapon==="plasma"?7:4,v:720,damage:w.damage*save.upgrades.damage}));p.cool=w.cool/save.upgrades.fireRate;snd(save.weapon==="plasma"?150:620,.04)}
function enemy(boss=false){if(boss){const final=mission===4,hp=(final?180:70)+mission*20;enemies.push({boss:true,x:W/2,y:-80,r:final?72:55,hp,max:hp,v:final?28:38,t:0,shoot:.7});return}const q=Math.random(),type=q>.8?"tank":q>.5?"zig":"scout";enemies.push({type,x:30+Math.random()*(W-60),y:-30,r:type==="tank"?27:17,hp:type==="tank"?5:1,v:70+mission*12+Math.random()*70,t:Math.random()*6,shoot:1+Math.random()*2})}
function hurt(n:number){health-=Math.max(0,n-save.upgrades.shield*5);p.flash=.12;snd(70,.08)}
function update(dt:number){const s=ships.find(v=>v.id===save.selected)!;let dx=(keys.has("a")||keys.has("arrowleft")?-1:0)+(keys.has("d")||keys.has("arrowright")?1:0),dy=(keys.has("w")||keys.has("arrowup")?-1:0)+(keys.has("s")||keys.has("arrowdown")?1:0),l=Math.hypot(dx,dy)||1;p.x=Math.max(22,Math.min(W-22,p.x+dx/l*s.speed*dt));p.y=Math.max(35,Math.min(H-30,p.y+dy/l*s.speed*dt));if(keys.has(" ")||keys.has("space"))fire();p.cool=Math.max(0,p.cool-dt);time+=dt;spawn-=dt;
if(missions[mission][2]!=="boss"&&spawn<=0&&!enemies.some(e=>e.boss)){enemy();spawn=Math.max(.28,.9-mission*.08)}if(missions[mission][2]==="boss"&&!bossSpawned&&time>3){enemy(true);bossSpawned=true}
stars.forEach(a=>{a.y+=a.s*dt;if(a.y>H){a.y=0;a.x=Math.random()*W}});shots.forEach(b=>b.y-=b.v*dt);shots=shots.filter(b=>b.y>-30);enemyShots.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});enemyShots=enemyShots.filter(b=>b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);
enemies.forEach(e=>{e.y+=e.v*dt;e.t+=dt;if(!e.boss)e.x+=Math.sin(e.t*2.2)*35*dt;e.shoot-=dt;if(e.shoot<=0){const a=Math.atan2(p.y-e.y,p.x-e.x);enemyShots.push({x:e.x,y:e.y,r:e.boss?7:5,vx:Math.cos(a)*(e.boss?190:150),vy:Math.sin(a)*(e.boss?190:150)});e.shoot=e.boss?.65:2+Math.random()*2}if(e.y>H+50){hurt(e.boss?25:10);e.y=-50}});
for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];for(let j=shots.length-1;j>=0;j--)if(hit(e,shots[j])){e.hp-=shots[j].damage;burst(shots[j].x,shots[j].y,5);shots.splice(j,1);if(e.hp<=0){score+=e.boss?1000:25;save.credits+=e.boss?400:10;objective=e.boss?1:score;burst(e.x,e.y,e.boss?60:20,e.boss?"#ff3f7f":"#ffb347");enemies.splice(i,1);break}}if(enemies[i]&&hit(p,enemies[i])){hurt(enemies[i].boss?35:20);burst(p.x,p.y,15,"#ff5470");enemies.splice(i,1)}}
for(let i=enemyShots.length-1;i>=0;i--)if(hit(p,enemyShots[i])){hurt(10);burst(p.x,p.y,7,"#ff5470");enemyShots.splice(i,1)}
const goal=missions[mission][3];objective=missions[mission][2]==="survive"?time:(missions[mission][2]==="boss"?objective:score);if(objective>=goal){save.missions=[...new Set([...save.missions,mission])];save.best=Math.max(save.best,score);saveIt();mission++;if(mission>=missions.length){running=false;O.classList.remove("hidden");M.innerHTML="<b>CAMPAIGN COMPLETE</b><br>The Interstellar Core has fallen.";A.textContent="RETURN TO HANGAR";A.onclick=()=>showHangar("Campaign complete.");return}showHangar("MISSION COMPLETE · Credits: "+save.credits);return}if(health<=0){running=false;O.classList.remove("hidden");M.textContent="MISSION FAILED";A.textContent="RETURN TO HANGAR";A.onclick=()=>showHangar("Your upgrades remain saved.")}}
function draw(){X.clearRect(0,0,W,H);stars.forEach(s=>{X.globalAlpha=.25+s.z*.2;X.fillStyle="#fff";X.fillRect(s.x,s.y,s.z,s.z*2)});X.globalAlpha=1;shots.forEach(b=>{X.fillStyle=save.weapon==="plasma"?"#d36bff":"#72e8ff";X.shadowBlur=15;X.shadowColor=X.fillStyle;X.beginPath();X.arc(b.x,b.y,b.r,0,Math.PI*2);X.fill()});enemyShots.forEach(b=>{X.fillStyle="#ff527d";X.beginPath();X.arc(b.x,b.y,b.r,0,Math.PI*2);X.fill()});enemies.forEach(e=>{X.save();X.translate(e.x,e.y);X.shadowBlur=e.boss?30:16;X.shadowColor=e.boss?"#ff3f7f":e.type==="tank"?"#b879ff":"#ffb347";X.fillStyle=X.shadowColor;X.beginPath();if(e.boss)X.arc(0,0,e.r,0,Math.PI*2);else{X.moveTo(0,e.r);X.lineTo(-e.r,-e.r);X.lineTo(0,-e.r*.35);X.lineTo(e.r,-e.r);X.closePath()}X.fill();X.restore();if(e.boss){X.fillStyle="#30111d";X.fillRect(e.x-70,e.y-e.r-18,140,7);X.fillStyle="#ff4e7d";X.fillRect(e.x-70,e.y-e.r-18,140*Math.max(0,e.hp/e.max),7)}});particles.forEach(q=>{X.globalAlpha=Math.max(0,q.life*2);X.fillStyle=q.col;X.fillRect(q.x,q.y,q.size,q.size)});X.globalAlpha=1;X.shadowBlur=20;X.shadowColor="#5de4ff";X.fillStyle="#5de4ff";X.beginPath();X.moveTo(p.x,p.y-27);X.lineTo(p.x-21,p.y+21);X.lineTo(p.x,p.y+13);X.lineTo(p.x+21,p.y+21);X.closePath();X.fill();X.shadowBlur=0;X.fillStyle="#b9d8ff";X.font="12px system-ui";X.fillText("Score "+score+" · Hull "+Math.max(0,Math.ceil(health))+" · Credits "+save.credits+" · "+weapons.find(w=>w.id===save.weapon)!.name,18,H-18)}
function loop(t:number){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
addEventListener("resize",resize);addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.code==="Space")e.preventDefault()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));A.onclick=launch;resize();showHangar("Choose a ship, install upgrades, and launch.");